var task1 = new TodoItem('This is our first task');
var task2 = new TodoItem('Eat pizza 🍕 yummy!!!');
var task3 = new TodoItem('Finish this iteration 1!! 🤓');
var task4 = new TodoItem('Finish this iteration 2!! 🤓');
var task5 = new TodoItem('Finish this iteration 3!! 🤓');
var myTodos = new TodoList();
myTodos.addTask(task1);
myTodos.addTask(task2);
myTodos.addTask(task3);
myTodos.addTask(task4);
myTodos.addTask(task5);
myTodos.listAllTasks();
myTodos.deleteTask(task3);
myTodos.deleteTask(task4);
myTodos.deleteTask(task5);
myTodos.listUncomplete();
